server:
  port: 8009
spring:
  application:
    name: sw-user-profile #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.175:3306/skyway_new?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: test
    password: test
  redis:
    host: 192.168.0.175
    port: 6379
    password: 123456
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:9999/eureka
#     enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
logging:
  level:
   root: debug

